export const movies = {
  list: [
    {
      title: "The Matrix",
      director: "Lana Wachowski, Lilly Wachowski",
      year: 1999,
      genre: ["Action", "Sci-Fi"],
      rating: 8.7,
    },
    {
      title: "The Matrix Reloaded",
      director: "Lana Wachowski, Lilly Wachowski",
      year: 2003,
      genre: ["Action", "Sci-Fi"],
      rating: 7.2,
    },
    {
      title: "Finding Nemo",
      director: "Andrew Stanton, Lee Unkrich",
      year: 2003,
      genre: ["Animation", "Adventure", "Comedy"],
      rating: 8.2,
    },
    {
      title: "Finding Dory",
      director: "Andrew Stanton, Angus McLane",
      year: 2016,
      genre: ["Animation", "Adventure", "Comedy"],
      rating: 8.7,
    },
    {
      title: "Interstellar",
      director: "Christopher Nolan",
      year: 2014,
      genre: ["Adventure", "Sci-Fi"],
      rating: 8.6,
    },
    {
      title: "50 first dates",
      director: "Peter Segal",
      year: 2004,
      genre: ["Comedy", "Romance"],
      rating: 6.8,
    },
    {
      title: "Fight Club",
      director: " David Fincher",
      year: 1999,
      genre: ["Drama"],
      rating: 8.8,
    },
    {
      title: "Pulp Fiction",
      director: "Quentin Tarantino",
      year: 1994,
      genre: ["Crime"],
      rating: 8.9,
    },
    {
      title: "Inglorious Basterds",
      director: "Quentin Tarantino",
      year: 2009,
      genre: ["War", "Adventure", "Drama"],
      rating: 7.1,
    },
    {
      title: "The Hobbit: An Unexpected Journey",
      director: "Peter Jackson",
      year: 2012,
      genre: ["Adventure", "Fantasy"],
      rating: 7.8,
    },
    {
      title: "The Hobbit: The Desolation of Smaug",
      director: "Peter Jackson",
      year: 2013,
      genre: ["Adventure", "Fantasy"],
      rating: 7.8,
    },
    {
      title: "The Hobbit: The Battle of the Five Armies",
      director: "Peter Jackson",
      year: 2014,
      genre: ["Adventure", "Fantasy"],
      rating: 7.4,
    },
    {
      title: "Avatar",
      director: "James Cameron",
      year: 2009,
      genre: ["Action", "Adventure", "Fantasy"],
      rating: 7.9,
    },
    {
      title: "Avatar: The Way of Water",
      director: "James Cameron",
      year: 2022,
      genre: ["Action", "Adventure", "Fantasy"],
      rating: 8,
    },
    {
      title: "Star Wars: Episode I - The Phantom Menace",
      director: "George Lucas",
      year: 1999,
      genre: ["Action", "Adventure", "Fantasy"],
      rating: 6.5,
    },
    {
      title: "Star Wars: Episode II - Attack of the Clones",
      director: "George Lucas",
      year: 2002,
      genre: ["Action", "Adventure", "Fantasy"],
      rating: 6.6,
    },
    {
      title: "Star Wars: Episode III - Revenge of the Sith",
      director: "George Lucas",
      year: 2005,
      genre: ["Action", "Adventure", "Fantasy"],
      rating: 7.6,
    },
    {
      title: "Star Wars: Episode IV - A New Hope",
      director: "George Lucas",
      year: 1977,
      genre: ["Action", "Adventure", "Fantasy"],
      rating: 8.6,
    },
    {
      title: "Star Wars: Episode V - The Empire Strikes Back",
      director: "Irvin Kershner",
      year: 1980,
      genre: ["Action", "Adventure", "Fantasy"],
      rating: 8.7,
    },
    {
      title: "Star Wars: Episode VI - Return of the Jedi",
      director: "Richard Marquand",
      year: 1983,
      genre: ["Action", "Adventure", "Fantasy"],
      rating: 8.3,
    },
    {
      title: "JAWS",
      director: "Steven Spielberg",
      year: 1975,
      genre: ["Adventure", "Thriller"],
      rating: 8.1,
    },
    {
      title: "Cocoon",
      director: "Ron Howard",
      year: 1985,
      genre: ["Comedy", "Drama", "Sci-Fi"],
      rating: 6.7,
    },
    {
      title: "The Lion King",
      director: "Roger Allers, Rob Minkoff",
      year: 1994,
      genre: ["Animation", "Adventure", "Drama"],
      rating: 8.5,
    },
    {
      title: "Cinema Paradiso",
      director: "Giuseppe Tornatore",
      year: 1988,
      genre: ["Drama", "Romance"],
      rating: 8.5,
    },
    {
      title: "Schindler”s List",
      director: "Steven Spielberg",
      year: 1993,
      genre: ["Biography", "Drama", "History"],
      rating: 9,
    },
    {
      title: "Birdy",
      director: "Steven Spielberg",
      year: 1984,
      genre: ["Drama", "War"],
      rating: 7.2,
    },
    {
      title: "The Godfather",
      director: "Francis Ford Coppola",
      year: 1972,
      genre: ["Drama", "Crime"],
      rating: 9.2,
    },
    {
      title: "The Great Train Robbery",
      director: "Edwin S. Porter",
      year: 1903,
      genre: ["Short", "Action", "Adventure"],
      rating: 6.9,
    },
    {
      title: "Trip to the Moon",
      director: "Georges Méliès",
      year: 1902,
      genre: ["Short", "Action", "Adventure"],
      rating: 8.2,
    },
    {
      title: "The Horse in Motion",
      director: "Eadweard Muybridge",
      year: 1878,
      genre: ["Documentary", "Short"],
      rating: "not rated",
    },
    {
      title: "Mamma Mia!",
      director: "Hyllida Lloyd",
      year: 2008,
      genre: ["Comedy", "Musical", "Romance"],
      rating: 6.5,
    },
    {
      title: "The Secret Garden",
      director: "Marc Munden",
      year: 2020,
      genre: ["Drama", "Family", "Fantasy"],
      rating: 5.6,
    },
    {
      title: "Wavelength",
      director: "Michael Snow",
      year: 1967,
      genre: ["Short", "Drama", "Experimental"],
      rating: 5.4,
    },
    {
      title: "SAW",
      director: "James Wan",
      year: 2004,
      genre: ["Horror", "Thriller", "Mystery"],
      rating: 7.6,
    },
    {
      title: "Upstream Color",
      director: "Shane Carruth",
      year: 2013,
      genre: ["Drama", "Sci-Fi", "Experimental"],
      rating: 6.5,
    },
    {
      title: "Un perro andaluz",
      director: "Luis Buñuel",
      year: 1929,
      genre: ["Short", "Horror", "Experimental"],
      rating: 7.7,
    },
    {
      title: "Ghostbusters",
      director: "Ivan Reitman",
      year: 1984,
      genre: ["Action", "Comedy", "Fantasy"],
      rating: 7.8,
    },
    {
      title: "Gremlins",
      director: "Joe Dante",
      year: 1984,
      genre: ["Comedy", "Fantasy", "Horror"],
      rating: 7.3,
    },
    {
      title: "Pink Floyd: The Wall",
      director: "Alan Parker",
      year: 1982,
      genre: ["Drama", "Fantasy", "Music"],
      rating: 8,
    },
    {
      title: "The Green Mile",
      director: "Frank Darabont",
      year: 1999,
      genre: ["Crime", "Drama", "Fantasy"],
      rating: 8.6,
    },
    {
      title: "Dune",
      director: "David Lynch",
      year: 1984,
      genre: ["Action", "Adventure", "Sci-Fi"],
      rating: 6.3,
    },
    {
      title: "Taxi Driver",
      director: "Martin Scorsese",
      year: 1976,
      genre: ["Crime", "Drama"],
      rating: 8.2,
    },
    {
      title: "Casablanca",
      director: "Michael Curtiz",
      year: 1942,
      genre: ["Drama", "Romance", "War"],
      rating: 8.5,
    },
    {
      title: "Citizen Kane",
      director: "Orson Welles",
      year: 1941,
      genre: ["Drama", "Mystery"],
      rating: 8.3,
    },
    {
      title: "The Dirty Dozen",
      director: "Robert Aldrich",
      year: 1967,
      genre: ["Action", "Adventure", "War"],
      rating: 7.7,
    },
    {
      title: "Titanic",
      director: "James Cameron",
      year: 1997,
      genre: ["Drama", "Romance"],
      rating: 7.9,
    },
    {
      title: "Apollo 13",
      director: "Ron Howard",
      year: 1995,
      genre: ["History", "Adventure", "Drama"],
      rating: 7.7,
    },
    {
      title: "Cast Away",
      director: "Robert Zemeckis",
      year: 2000,
      genre: ["Drama", "Adventure", "Romance"],
      rating: 7.8,
    },
    {
      title: "Coco",
      director: "Lee Unkrich, Adrian Molina",
      year: 2017,
      genre: ["Animation", "Adventure", "Comedy"],
      rating: 8.4,
    },
    {
      title: "Good Will Hunting",
      director: "Gus Van Sant",
      year: 1997,
      genre: ["Drama", "Romance"],
      rating: 8.3,
    },
    {
      title: "Chariots of Fire",
      director: "Hugh Hudson",
      year: 1981,
      genre: ["Biography", "Drama", "Sport"],
      rating: 7.1,
    },
    {
      title: "Jurassic World",
      director: "Colin Trevorrow",
      year: 2015,
      genre: ["Action", "Adventure", "Sci-Fi"],
      rating: 6.9,
    },
    {
      title: "The Truman Show",
      director: "Colin Trevorrow",
      year: 1998,
      genre: ["Comedy", "Drama"],
      rating: 8.2,
    },
    {
      title: "The Gods Must Be Crazy",
      director: "Jamie Uys",
      year: 1980,
      genre: ["Adventure", "Comedy"],
      rating: 7.3,
    },
  ],
};
